# Generated by /tmp/gen_chillu_sed.py (see AGENTS.md) — DO NOT HAND-EDIT.
# 1) non-atomic chillu C+virama+ZWJ -> atomic U+0D7A-U+0D7F.
# 2) delete stray ZWJ/ZWNJ/BOM left after conversion (invisible junk
#    that otherwise makes known words unanalysable, e.g. trailing ZWJ).
s/ക്‍/ൿ/g
s/ണ്‍/ൺ/g
s/ന്‍/ൻ/g
s/ര്‍/ർ/g
s/ല്‍/ൽ/g
s/ള്‍/ൾ/g
s/‍//g
s/‌//g
s/﻿//g
